version: "3.8"

services:
  rabbitmq:
    container_name: rabbitmq-container
    image: rabbitmq:3.13-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
    deploy:  
      resources:
        limits:
          cpus: "0.5"
          memory: "500M"

